#version: '3.8'

services:
  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    hostname: mongodb
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
      #- ./mongo-backend/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    restart: always

  nodejs-backend:
    build: ./nodejs-backend/
    hostname: "backend"
    ports:
      - 8080:8080
    volumes:
      - ./nodejs-backend/nodejs/server.js:/src/server.js
      - ./nodejs-backend/nodejs/.env:/src/.env
      - ./nodejs-backend/nodejs/packages/:/src/packages/
      - ./nodejs-backend/nodejs/docs/:/src/docs/
    restart: always

  vuejs-frontend:
    build: ./vuejs-frontend/
    hostname: "frontend"
    ports:
      - 80:80
    volumes:
      - ./vuejs-frontend/vue/dist/:/usr/share/nginx/html/
    restart: always

volumes:
  dbdata: