version: "3.9"

services:
# MongoDB Database
  mongodb:
    image: mongo:latest
    restart: always
    hostname: mongodb
    command: mongod --auth
    ports:
      - 27017:27017
    networks:
      - backend
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes: 
      - mongodbdata:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

# Workbench for MongoDB Database  
  mongo-express:
    image: mongo-express:latest
    restart: always
    hostname: mongo-express
    ports:
      - 27000:8081
    networks:
      - backend
      - frontend
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017
    depends_on:
      - mongodb

  nodejs-frontend:
    build: images/nodejs-frontent/
    ports:
      - 80:80
      - 443:443

  nodejs-backend:
    build: images/nodejs-backend/
    ports:
      - 8080:8080

networks:
  frontend:
  backend:

volumes:
  mongodbdata:
    driver: local